services:
  dnsmasq:
    image: dockurr/dnsmasq
    container_name: dnsmasq
    ports:
      - 32053:53/udp
      - 32053:53/tcp
    volumes:
      - ./dnsmasq.d/:/etc/dnsmasq.d/ # directorios de modulos de configuracion
      - ./dnsmasq.conf:/etc/dnsmasq.conf # configuracion global
    restart: unless-stopped
